### ISSUE TITLE
CF v231

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-final-release-election#3]
cf-release Release Candidate SHA for v231 Deploy:
[f67ebb734d45ba17dacc8e89c5f2758a50a844a9](https://github.com/cloudfoundry/cf-release/commit/f67ebb734d45ba17dacc8e89c5f2758a50a844a9)

Details:
Not Available due to limitation in [`announce-rc` Concourse job](https://mega.ci.cf-app.com/pipelines/release/jobs/announce-rc/builds/45).  This [will eventually be fixed](https://www.pivotaltracker.com/story/show/114047299).

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @Amit-PivotalLabs
- **Comments**: This SHA is fine for Release Integration, but there are some things to note:
  - CC api_z1/1 is in stopped state on A1, not sure why it's stuck in that state, leaving there for potential investigation. **Sent email to CAPI and BOSH teams for investigation**
  - route-registrar healthcheck stuff is still WIP
  - We have a known issue with DEA drain, it just surfaced recently but appears to be a bug in the code that's a couple years old, so we won't be blocking a release on this
  - Buildpacks (except for Java) are part of a separate release, and are now being consumed by cf-release as a submodule with symlinks, and colocated jobs with the CC (rather than packages dependencies of CC)
  - Loggregator has also introduced a backwards incompatible change in some of the job spec configuration, so release notes will have to tell users to move their config to a different key in the manifest
  - Datadog seemed to be showing significant increase in system CPU usage since a recent deploy. Around 19 Feb between 1200 and 1300 Pacific, appeared to be an increase of about 4 units in BOSH system CPU percentage across all runner VMs.  This means each 4 core machine has increased total CPU utilization of about 0.4%.  SSHing onto some of the high CPU VMs doesn't appear to show any new high CPU processes, seems unlikely that there are many longtail processes contributing.  Nothing in the A1 deploy job history looks suspicious.
  - Datadog also seemed to be showing a significant increase in requests to router (but not total routes). Looking back over the past month, the increase in total requests to router does not seem as significant

----
@Amit-PivotalLabs, @ryanmoran:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1::
- **Decider**: @Amit-PivotalLabs
- **Comments**: Good to go.  It's worth noting that this SHA does *not* include the postgres 9.4.6 bump to address [USN-2894-1](http://www.ubuntu.com/usn/usn-2894-1/)

----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: shannon
- **Comments**:

----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: Sree
- **Comments**: 

----
@Jim-Campbell, @wfernandes
Does this cf-release SHA look good for the LAMB team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @wfernandes
- **Comments**: 
  - Switched to go1.5.3
  - Renames Metron-Doppler TLS properties
  - Sanitize syslog-drain logs
  - Update gogo/protobuf in sonde-go

----
@dieucao, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: 
- **Decider**: @dieucao
- **Comments**: This includes changes to  how blobstore is specified. Does not yet change default to webdav

----
@Dannyzen, @jtarchie:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: 
- **Decider**: @dannyzen
- **Comments**:  

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @nebhale
- **Comments**: `v3.6`

----
@ematpl, @luan:
Can you provide a compatible diego-release SHA?
- **Approval**:  :+1:
- **Decider**: @ematpl
- **Comments**: [Diego 0.1454.0 / GL 0.333.0 / etcd 36 are compatible](https://github.com/cloudfoundry-incubator/diego-cf-compatibility/blob/master/compatibility-v2.csv#L288).

----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @fraenkel
- **Comments**:

**Comment by roxtar** [comment]
Switched loggregator approver to @wfernandes since he is the new anchor. @Amit-PivotalLabs can you make sure he has access to this repository.

**Comment by Amit-PivotalLabs** [comment]
@roxtar done.

**Comment by shalako** [comment]
Three teams left
@sreetummidi, @mbhave
@Jim-Campbell, @wfernandes
@dieucao, @utako

**Comment by dieucao** [comment]
Just waiting for @sreetummidi and @mbhave to approve.

**Comment by sreetummidi** [comment]
UAA Approval Updated !

Thanks,
Sree Tummidi
Sr. Product Manager
Identity - Pivotal Cloud Foundry

**Comment by Amit-PivotalLabs** [comment]
```
$ git push origin f67ebb734d45ba17dacc8e89c5f2758a50a844a9:release-elect
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:cloudfoundry/cf-release
   3de108d..f67ebb7  f67ebb734d45ba17dacc8e89c5f2758a50a844a9 -> release-elect
```

**Comment by Amit-PivotalLabs** [comment]
You can follow the final release build here: https://mega.ci.cf-app.com/pipelines/cf-release/jobs/create-final-release/builds/14

**Comment by Amit-PivotalLabs** [comment]
Previous build failed due to changes in CI scripts, fixed and triggered new build: https://mega.ci.cf-app.com/pipelines/cf-release/jobs/create-final-release/builds/15

**Comment by Amit-PivotalLabs** [comment]
CF v231 is now available: http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=231
