### ISSUE TITLE
CF v232

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-final-release-election#4]
cf-release Release Candidate SHA for v232:
[10e395f72a556d93903013562d808b52bd7d23d1](https://github.com/cloudfoundry/cf-release/commit/10e395f72a556d93903013562d808b52bd7d23d1)

Details:
Not Available due to change in `announce-rc` Concourse job not compatible with previous CF v231.  This will be fixed as of next final release.

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:/:-1:
- **Decider**:
- **Comments**:

----
@Amit-PivotalLabs, @zankich:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:/:-1:
- **Decider**:
- **Comments**:

----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: shannon
- **Comments**:

----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @mbhave
- **Comments**: uaa-3.2.1

----
@Jim-Campbell, @wfernandes
Does this cf-release SHA look good for the LAMB team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: Jim Campbell
- **Comments**:

----
@dieucao, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:/:-1:
- **Decider**:
- **Comments**:

----
@Dannyzen, @jtarchie:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @dannyzen
- **Comments**:  We're excited.

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @nebhale
- **Comments**: `v3.6`

----
@ematpl, @luan:
Can you provide a compatible diego-release SHA?
- **Approval**: :-1:
- **Decider**: @ematpl
- **Comments**: I don't see a compatibility record for a Diego final release in https://github.com/cloudfoundry-incubator/diego-cf-compatibility/blob/master/compatibility-v2.csv.

----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1:
- **Decider**: @fraenkel
- **Comments**:

**Comment by Amit-PivotalLabs** [comment]
cf-release Release Candidate SHA for v232:
[2cb91185493a8a66b788a3b9626a600f081175bb](https://github.com/cloudfoundry/cf-release/commit/2cb91185493a8a66b788a3b9626a600f081175bb)

Details:
N/A

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Amit-PivotalLabs, @zankich:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Jim-Campbell, @wfernandes:
Does this cf-release SHA look good for the Loggregator team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@SocalNick, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Dannyzen, @jtarchie:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@ematpl, @luan:
Can you provide a compatible diego-release SHA?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

**Comment by Amit-PivotalLabs** [comment]
cf-release Release Candidate SHA for v232:
[0034478fdc9cb6daf54f9a4bbe532a03e39ed903](https://github.com/cloudfoundry/cf-release/commit/0034478fdc9cb6daf54f9a4bbe532a03e39ed903)

Details:
N/A

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.
----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@Amit-PivotalLabs, @zankich:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@Jim-Campbell, @wfernandes:
Does this cf-release SHA look good for the Loggregator team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@SocalNick, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@Dannyzen, @jtarchie:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@ematpl, @luan:
Can you provide a compatible diego-release SHA?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:
----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

**Comment by ematpl** [comment]
@Amit-PivotalLabs looks like https://runtime.ci.cf-app.com/pipelines/cf-release/jobs/a1-diego-deploy-and-test/builds/76 was a successful run of https://github.com/cloudfoundry/cf-release/commit/0034478fdc9cb6daf54f9a4bbe532a03e39ed903 against Diego on A1, but there's no record in https://github.com/cloudfoundry-incubator/diego-cf-compatibility/blob/master/compatibility-v2.csv. What do you want to do about recording this manually until that part of https://www.pivotaltracker.com/story/show/114914443 is done?

**Comment by dieucao** [comment]
Looks like a commit with a loggregator bump made it through all but the openstack pipeline
https://github.com/cloudfoundry/cf-release/tree/67a5f78e9bd1443ad4015afe462d05b0f366e26c

@Jim-Campbell is that the fix? Have you had a chance to verify the fix?

**Comment by wfernandes** [comment]
@dieucao I verified that everything looks good on A1. Log files are created with the correct permissions and logs are being written to them. The openstack build failed due to timeout issue during deployment.

**Comment by Amit-PivotalLabs** [comment]
cf-release Release Candidate SHA for v232:
[67a5f78e9bd1443ad4015afe462d05b0f366e26c](https://github.com/cloudfoundry/cf-release/commit/67a5f78e9bd1443ad4015afe462d05b0f366e26c)

Details:
N/A

**Please read these instructions, as they changed on 4 Nov 2015.**
- Edit this comment by setting the approval for your section (delete the thumb you don't want)
- Also set your GitHub handle as the approver
- Add any additional comments you may have in your section
- If you notice you are the last person to set your approval, as a courtesy please also add a new comment to the issue saying so, so that we get GitHub notifications that all approvals are done.

----
@Amit-PivotalLabs, @robdimsdale:
Does this cf-release SHA look good for the release integration team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Amit-PivotalLabs, @zankich:
Does this cf-release SHA look good for the infrastructure team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@shalako, @crhino:
Does this cf-release SHA look good for the routing team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@sreetummidi, @mbhave:
Does this cf-release SHA look good for the identity team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Jim-Campbell, @wfernandes:
Does this cf-release SHA look good for the Loggregator team? Do the a1 logging metrics look nominal?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@SocalNick, @utako:
Does this cf-release SHA look good for the CAPI team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@Dannyzen, @jtarchie:
Does this cf-release SHA look good for the Buildpacks and Stacks team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@nebhale, @cgfrost:
Does this cf-release SHA look good for the Java Buildpack team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@ematpl, @luan:
Can you provide a compatible diego-release SHA?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

----
@fraenkel, @sykesm:
Does this cf-release SHA look good for the DEA + HM9000 team?  Any bugs, regressions, or incomplete features of concern?
- **Approval**: :+1: / :-1:
- **Decider**:
- **Comments**:

**Comment by dieucao** [comment]
@Amit-PivotalLabs Thumbs up across the board!

**Comment by Amit-PivotalLabs** [comment]
```
$ git push origin 67a5f78e9bd1443ad4015afe462d05b0f366e26c:release-elect
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:cloudfoundry/cf-release
   f67ebb7..67a5f78  67a5f78e9bd1443ad4015afe462d05b0f366e26c -> release-elect
```

**Comment by Amit-PivotalLabs** [comment]
Build in progress: https://runtime.ci.cf-app.com/pipelines/cf-release-final/jobs/create-final-release/builds/2

**Comment by Amit-PivotalLabs** [comment]
Final release has been cut:

* Commit on master: https://github.com/cloudfoundry/cf-release/commit/d58979fa9d54eeeebe71beca527e7745c4db237a
* Release on bosh.io: http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=232
